import 'package:flutter/material.dart';

String version = "0.0.0A";
bool beta = true;

// had ChatGPT make this since I was too lazy lol
final List<Map<String, dynamic>> appIcons = [
  {"icon": Icons.home, "text": "Home"},
  {"icon": Icons.search, "text": "Search"},
  {"icon": Icons.settings, "text": "Settings"},
  {"icon": Icons.person, "text": "Profile"},
  {"icon": Icons.favorite, "text": "Favorites"},
  {"icon": Icons.notifications, "text": "Notifications"},
  {"icon": Icons.shopping_cart, "text": "Cart"},
  {"icon": Icons.chat, "text": "Chat"},
  {"icon": Icons.camera, "text": "Camera"},
  {"icon": Icons.map, "text": "Map"},
  {"icon": Icons.alarm, "text": "Alarm"},
  {"icon": Icons.book, "text": "Book"},
  {"icon": Icons.calendar_today, "text": "Calendar"},
  {"icon": Icons.call, "text": "Call"},
  {"icon": Icons.email, "text": "Email"},
  {"icon": Icons.folder, "text": "Folder"},
  {"icon": Icons.music_note, "text": "Music"},
  {"icon": Icons.video_library, "text": "Videos"},
  {"icon": Icons.file_copy, "text": "Files"},
  {"icon": Icons.lock, "text": "Lock"},
  {"icon": Icons.share, "text": "Share"},
  {"icon": Icons.wifi, "text": "Wi-Fi"},
  {"icon": Icons.bluetooth, "text": "Bluetooth"},
  {"icon": Icons.cloud, "text": "Cloud"},
  {"icon": Icons.sunny, "text": "Weather"},
  {"icon": Icons.battery_full, "text": "Battery"},
  {"icon": Icons.sports_soccer, "text": "Sports"},
  {"icon": Icons.directions_car, "text": "Car"},
  {"icon": Icons.train, "text": "Train"},
  {"icon": Icons.flight, "text": "Flight"},
  {"icon": Icons.pets, "text": "Pets"},
  {"icon": Icons.restaurant, "text": "Restaurant"},
  {"icon": Icons.coffee, "text": "Coffee"},
  {"icon": Icons.fitness_center, "text": "Fitness"},
  {"icon": Icons.local_hospital, "text": "Hospital"},
  {"icon": Icons.school, "text": "School"},
  {"icon": Icons.work, "text": "Work"},
  {"icon": Icons.lightbulb, "text": "Ideas"},
  {"icon": Icons.security, "text": "Security"},
  {"icon": Icons.shopping_bag, "text": "Shopping"},
  {"icon": Icons.code, "text": "Code"},
  {"icon": Icons.build, "text": "Tools"},
  {"icon": Icons.brush, "text": "Art"},
  {"icon": Icons.science, "text": "Science"},
  {"icon": Icons.gavel, "text": "Legal"},
  {"icon": Icons.park, "text": "Park"},
  {"icon": Icons.movie, "text": "Movies"},
  {"icon": Icons.headphones, "text": "Headphones"},
  {"icon": Icons.star, "text": "Star"},
  {"icon": Icons.emoji_emotions, "text": "Emojis"},
  {"icon": Icons.palette, "text": "Colors"},
  {"icon": Icons.light_mode, "text": "Light Mode"},
  {"icon": Icons.dark_mode, "text": "Dark Mode"},
  {"icon": Icons.account_balance, "text": "Bank"},
];